### ISSUE TITLE
erreur proxycheck.tcl

### ISSUE THREAD

**Issue by bouba89** [MalaGaM/TCL-PROXYCHECK#1]
Tcl error in file 'proxycheck.conf':
child process exited abnormally
    while executing
"exec which whois"
    (in namespace eval "::ProxyCheck" script line 11)
    invoked from within
"namespace eval ::ProxyCheck {
        variable config
        variable ns     [namespace current]
        variable CONNECT_ID
        variable BOT_ID
        variable HTTP
        variable WHOIS
        ..."
    (file "scripts/ProxyCheck.tcl" line 26)

**Comment by ZarTek-Creole** [comment]
Il vous manque le binaire "whois" ou vous exécuté dans un environnement non linux (genre cygwin)

sous debian : `apt install whois`

Attention, c'est un script non fini du tout. Des erreurs peuvent surgir c'est assez expérimental (pour l'instant)

**Comment by bouba89** [comment]
j'ai bien lancer le link mai j'ai une erreur de uid 

 Bad UID: 00CAAAAA@ From: ProxyCheck.Tchat-Radio.com ProxyCheck.Tchat-Radio.com[server.tchat-radio.com]

**Comment by ZarTek-Creole** [comment]
Cela semble être un autres problèmes merci de créer un issue par problème -> #2
